"""Generated bytes and mocked transport only; never contact/read BDF sources."""

import contextlib
import copy
from email.message import Message
import hashlib
import importlib.util
import io
import json
from pathlib import Path
import tempfile
import time
from types import SimpleNamespace
import unittest
from unittest import mock


SCRIPT = Path(__file__).resolve().parents[1] / "scripts/acquire_inner_speech.py"
SPEC = importlib.util.spec_from_file_location("inner_speech_acquisition_tested", SCRIPT)
acq = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(acq)


def generated_header(labels=None, records=1):
    labels = labels or [f"{bank}{i}" for bank in "ABCD" for i in range(1, 33)] + \
        [f"EXG{i}" for i in range(1, 9)] + ["Status"]
    count = len(labels)

    def field(value, width):
        return str(value).encode("ascii").ljust(width, b" ")

    fixed = (b"\xffBIOSEMI" + field("PATIENT_SECRET", 80) + field("RECORDING_SECRET", 80) +
             field("01.01.00", 8) + field("01.02.03", 8) + field(256 * (count + 1), 8) +
             field("24BIT", 44) + field(records, 8) + field(1, 8) + field(count, 4))
    variable = b"".join(field(label, 16) for label in labels)
    for width, value in ((80, ""), (8, "uV"), (8, -262144), (8, 262143), (8, -8388608),
                         (8, 8388607), (80, ""), (8, 1024), (32, "")):
        variable += field(value, width) * count
    header = fixed + variable
    return header, len(header) + 3 * records * count * 1024


class FakeBudget:
    def __init__(self):
        self.started = time.monotonic()
        self.deadline = self.started + 3600
        self.peak_rss = self.payload_bytes = self.metadata_bytes = 0

    def check(self):
        pass

    def timeout(self):
        return 30.0

    def account(self, amount, *, payload):
        if payload:
            self.payload_bytes += amount
        else:
            self.metadata_bytes += amount


class FakeResponse:
    def __init__(self, body, url, *, status=200, length=None, encoding=None, version=None):
        self.body = io.BytesIO(body)
        self.url, self.status = url, status
        self.headers = Message()
        self.headers["Content-Length"] = str(len(body) if length is None else length)
        if encoding is not None:
            self.headers["Content-Encoding"] = encoding
        if version is not None:
            self.headers["x-amz-version-id"] = version
        self.read_sizes, self.timeouts = [], []
        self.fp = SimpleNamespace(raw=SimpleNamespace(_sock=SimpleNamespace(settimeout=self.timeouts.append)))

    def geturl(self):
        return self.url

    def read1(self, size):
        self.read_sizes.append(size)
        return self.body.read(size)

    def __enter__(self):
        return self

    def __exit__(self, *args):
        self.body.close()


class FakeOpener:
    def __init__(self, response=None, error=None):
        self.response, self.error, self.calls = response, error, 0

    def open(self, request, *, timeout):
        self.calls += 1
        if self.error:
            raise self.error
        return self.response


class AcquisitionTests(unittest.TestCase):
    def test_frozen_manifest_and_fail_closed_mutations(self):
        original = acq.load_manifest()
        mutations = [
            lambda m: m["files"][0].update(path="../../outside.bdf"),
            lambda m: m["files"][0].update(path=m["files"][1]["path"]),
            lambda m: m["files"].pop(),
            lambda m: m.update(source_commit="0" * 40),
            lambda m: m["files"][0].update(size_bytes=11 * acq.GIB),
            lambda m: m["files"][0].update(md5="0" * 32),
            lambda m: m["files"][0].update(url="https://example.org/payload"),
            lambda m: m["files"][0].update(url=m["files"][0]["url"] + "&other=1"),
            lambda m: m["files"][0].update(s3_version_id="different"),
            lambda m: m["files"][0].update(url=m["files"][0]["url"].split("?")[0], s3_version_id=None),
            lambda m: m["metadata_files"][0].update(path="sub-01/events.tsv"),
            lambda m: m["metadata_files"][0].update(url=acq.RAW + "../README"),
            lambda m: m["resource_limits"].update(wall_seconds=3601),
        ]
        for mutation in mutations:
            changed = copy.deepcopy(original)
            mutation(changed)
            with self.subTest(mutation=mutation), self.assertRaises(acq.Refusal):
                acq.validate_manifest(changed)

    def test_dry_run_has_no_network_or_optional_dependency(self):
        with mock.patch.dict("sys.modules", {"psutil": None}), \
                mock.patch.object(acq.urllib.request, "build_opener", side_effect=AssertionError("No network")), \
                contextlib.redirect_stdout(io.StringIO()) as output:
            self.assertEqual(acq.main([]), 0)
        self.assertEqual(json.loads(output.getvalue())["network_requests"], 0)

    def test_budget_enforces_wall_memory_storage_and_metadata(self):
        process = SimpleNamespace(memory_info=lambda: SimpleNamespace(rss=1024))
        with mock.patch.dict("sys.modules", {"psutil": SimpleNamespace(Process=lambda: process)}), \
                mock.patch.object(acq.time, "monotonic", return_value=100), \
                mock.patch.object(acq.shutil, "disk_usage", return_value=SimpleNamespace(free=100 * acq.GIB)):
            budget = acq.Budget(Path("generated"))
            self.assertEqual(budget.timeout(), 60)
            budget.deadline = 104
            self.assertEqual(budget.timeout(), 4)
            for field, value in (("deadline", 99), ("payload_bytes", acq.PAYLOAD_LIMIT + 1),
                                 ("metadata_bytes", acq.METADATA_LIMIT), ("peak_rss", acq.GIB + 1)):
                original = getattr(budget, field)
                setattr(budget, field, value)
                with self.subTest(field=field), self.assertRaises(acq.Refusal):
                    budget.check()
                setattr(budget, field, original)
            with mock.patch.object(acq.shutil, "disk_usage", return_value=SimpleNamespace(free=acq.DISK_FLOOR - 1)), \
                    self.assertRaisesRegex(acq.Refusal, "disk_floor"):
                budget.check()

    def test_header_only_geometry_and_sanitization_including_extra_channel(self):
        header, size = generated_header()
        summary = acq.parse_bdf_header(header, size)
        self.assertEqual(summary["channel_count"], 137)
        self.assertNotIn("SECRET", json.dumps(summary))
        self.assertFalse(summary["sample_or_status_values_parsed"])
        labels = [f"{bank}{i}" for bank in "ABCD" for i in range(1, 33)] + \
            [f"EXG{i}" for i in range(1, 9)] + ["Resp", "Status"]
        extra, extra_size = generated_header(labels)
        self.assertEqual(acq.parse_bdf_header(extra, extra_size)["additional_channels"], 1)
        bad_inputs = [(header[:255], size), (header[:-1], size), (header + b"x", size),
                      (header, size + 1), (b"0       " + header[8:], size),
                      (header.replace(b"EXG7            ", b"Other           ", 1), size),
                      (header[:252] + b"513 " + header[256:], size),
                      (header[:244] + b"2       " + header[252:], size)]
        for changed, changed_size in bad_inputs:
            with self.subTest(length=len(changed)), self.assertRaises(acq.Refusal):
                acq.parse_bdf_header(changed, changed_size)
        reads = []

        class HeaderStream(io.BytesIO):
            def read(self, amount=-1):
                reads.append(amount)
                return super().read(amount)

        with mock.patch.object(Path, "open", return_value=HeaderStream(header + b"UNREAD_BODY")):
            acq.inspect_header(Path("generated.bdf"), size)
        self.assertEqual(reads, [256, 137 * 256])

    def test_stream_verifies_bdf_hash_and_metadata_git_blob_without_resume(self):
        header, size = generated_header()
        body = header + b"\0" * (size - len(header))
        item = {"path": "generated.bdf", "url": "https://generated.invalid/a", "size_bytes": size,
                "md5": hashlib.md5(body).hexdigest(), "s3_version_id": "v1"}
        with tempfile.TemporaryDirectory() as directory:
            destination = Path(directory) / item["path"]
            response = FakeResponse(body, item["url"], version="v1")
            opener = FakeOpener(response)
            receipt = acq.download(item, destination, FakeBudget(), opener=opener)
            self.assertEqual(receipt["sha256"], hashlib.sha256(body).hexdigest())
            self.assertTrue(destination.exists())
            self.assertFalse(destination.with_suffix(".bdf.partial").exists())
            self.assertTrue(all(0 < amount <= acq.CHUNK for amount in response.read_sizes))
            self.assertTrue(all(0 < timeout <= 60 for timeout in response.timeouts))
            with self.assertRaisesRegex(acq.Refusal, "destination_exists"):
                acq.download(item, destination, FakeBudget(), opener=opener)
            self.assertEqual(opener.calls, 1)
            metadata = b"Generated metadata only."
            record = {"path": "README", "url": "https://generated.invalid/meta", "size_bytes": len(metadata),
                      "git_blob_sha1": acq.blob_sha1(metadata)}
            receipt = acq.download(record, Path(directory) / "README", FakeBudget(), metadata=True,
                                   opener=FakeOpener(FakeResponse(metadata, record["url"])))
            self.assertEqual(receipt["git_blob_sha1"], record["git_blob_sha1"])

    def test_transport_hash_and_header_refusals_leave_partial_no_retry(self):
        body = b"generated-only"
        base = {"path": "generated.bdf", "url": "https://generated.invalid/a", "size_bytes": len(body),
                "md5": hashlib.md5(body).hexdigest(), "s3_version_id": "v1"}
        cases = [(dict(status=302), None), (dict(length=len(body) + 1), None),
                 (dict(encoding="gzip"), None), (dict(version="wrong"), None),
                 (dict(), "0" * 32), (dict(), None)]  # final case: invalid BDF header
        for options, wrong_hash in cases:
            with self.subTest(options=options, wrong_hash=wrong_hash), tempfile.TemporaryDirectory() as directory:
                item = {**base, "md5": wrong_hash or base["md5"]}
                response = FakeResponse(body, item["url"], **{**{"version": "v1"}, **options})
                opener = FakeOpener(response)
                destination = Path(directory) / "generated.bdf"
                with self.assertRaises(acq.Refusal):
                    acq.download(item, destination, FakeBudget(), opener=opener)
                self.assertFalse(destination.exists())
                self.assertTrue(Path(str(destination) + ".partial").exists())
                self.assertEqual(opener.calls, 1)
        with self.assertRaisesRegex(acq.Refusal, "redirect_refused"):
            acq.NoRedirect().redirect_request(None, None, 302, "", {}, "https://elsewhere.invalid")

    def test_transaction_failure_is_sanitized_and_existing_root_refuses(self):
        with tempfile.TemporaryDirectory() as directory:
            output, result = Path(directory) / "new-run", Path(directory) / "result.json"
            opener = FakeOpener(error=acq.Refusal("redirect_refused"))
            with mock.patch.object(acq, "OUTPUT", output), \
                    mock.patch.object(acq.shutil, "disk_usage", return_value=SimpleNamespace(free=100 * acq.GIB)):
                with self.assertRaisesRegex(acq.Refusal, "redirect_refused"):
                    acq.acquire(acq.load_manifest(), output, result_path=result, budget=FakeBudget(), opener=opener)
                failure = json.loads((output / "acquisition_failure.json").read_text())
                self.assertEqual(failure["failure_code"], "redirect_refused")
                self.assertTrue((output / "README.partial").exists())
                self.assertFalse(result.exists())
                with self.assertRaisesRegex(acq.Refusal, "existing_run_or_result"):
                    acq.acquire(acq.load_manifest(), output, result_path=result, budget=FakeBudget(), opener=opener)
            self.assertEqual(opener.calls, 1)


if __name__ == "__main__":
    unittest.main()
